### PR TITLE
Fix typo in error message.

### PR DESCRIPTION
**Pull request by frewsxcv**

### CODE REVIEW

**Comment by PaulGrandperrin** [comment]
Yeah my first PR !
Thank you @frewsxcv :-D
I think I saw that bors is available on `rust-fuzz` so I'll try that
 @bors r+

**Comment by PaulGrandperrin** [comment]
Nothing's happening, am I missing something?

**Comment by frewsxcv** [comment]
@PaulGrandperrin i think you need to omit the `@` sign

bors r=PaulGrandperrin

**Comment by frewsxcv** [comment]
bors r=PaulGrandperrin

**Comment by frewsxcv** [comment]
ah i had to enable it in the web interface: https://bors.tech

**Comment by PaulGrandperrin** [comment]
Awesome, it looks like it's working!
It takes forever to pass the tests, I went a little crazy with the integration tests ;-)

**Comment by PaulGrandperrin** [comment]
OSX VMs on Travis seems to be broken right now.
I disabled them and also fixed `.travis.yml` to not try to build the "staging.tmp" branch.
I then rebased this PR against master, and it should work, hopefully.

**Comment by PaulGrandperrin** [comment]
Wow, that was laborious XD

**Pull request merged**
