### PR TITLE
refactor: use docopt, anyhow, fs-err, which crates to simplify and st…

### PR DESCRIPTION
**Pull request by drahnr**
…ructure

This remedies _some_ of the internal TODOs and yields better error messages.

Motivation is, to allow additional verifyable arguments to enhance practical usability without having to re-read various help texts on which param gets passed to which process.

### CODE REVIEW

**Comment by drahnr** [comment]
So `docopt` does not allow a unparsed chunk of trailing params as it seems :facepalm: going for clap next then.

**Comment by drahnr** [comment]
Not sure what causes the linkage error `__sanitizer_cov_trace_const_cmp8`

**Comment by drahnr** [comment]
This is ready for review :)

**Comment by PaulGrandperrin** [comment]
Hello @drahnr,
This is a big PR with lots of changes! Too big for me to review at once.
I'll start with the first commit which already contains a few different things:
- **docopt** : according to https://github.com/docopt/docopt.rs  this crate is unmaintained and the author recommends using `clap` or `structopt`. I'm already using `structopt` in other projects and I really like it but I thought that it might be a little overkill for such a simple use-case. For this simple project, I try very hard to only add dependencies when really useful and when the crate enjoys a healthy state of maintenance.
I don't know how much `structopt` would add to the compile-time, but I fear that pulling `serde` and co will add a lot for little benefit.
- **anyhow** : I like this crate and maybe it's worth adding! I'll add a few comments in the code later, but I saw many changes making the status code of the child process being printed out to `stdout` instead of being properly "forwarded" to the parent process exit code. My goal here was to make the `honggfuzz-rs`  wrapper as thin and transparent as possible (to minimize surprises and also maintenance).
- **fs-err** : The crate idea is nice but it'd still rather stick to the `std` for the reasons cited above.
- **which**  is nice :)
- `BuildType::ProfileWithGrcov` and `BuildType::Debug` have been refactored in a way that does not preserve the semantics of the previous code. Now `BuildType::Debug` will compile in `--release` mode which is not correct.
- This commit also includes a lot of format changes and other minor changes which I guess might partially come from `cargo fmt` and/or `cargo clippy`. It would be easier to review them in separate and later commits, or better, PRs.
- It seems your PR is based on an obsolete version of `master` because some of the latest changes I made have been deleted by your commit somehow (see https://github.com/rust-fuzz/honggfuzz-rs/commit/a6cb56d450751695dd4fe259845800fec24eac94)

**Comment by drahnr** [comment]
>     * **docopt** : according to https://github.com/docopt/docopt.rs  this crate is unmaintained and the author recommends using `clap` or `structopt`. I'm already using `structopt` in other projects and I really like it but I thought that it might be a little overkill for such a simple use-case. For this simple project, I try very hard to only add dependencies when really useful and when the crate enjoys a healthy state of maintenance.
>       I don't know how much `structopt` would add to the compile-time, but I fear that pulling `serde` and co will add a lot for little benefit.

Mostly went for it since I am in the same situation with `docopt`, and I like the fact that one writes the help message essentially, the rest is derived.

>     * **anyhow** : I like this crate and maybe it's worth adding! I'll add a few comments in the code later, but I saw many changes making the status code of the child process being printed out to `stdout` instead of being properly "forwarded" to the parent process exit code. My goal here was to make the `honggfuzz-rs`  wrapper as thin and transparent as possible (to minimize surprises and also maintenance).

In that case, an explicit encoding with `thiserror` and error variants might be the better approach. I would rather have it a bit thicker and provide more output as needed.

>     * **fs-err** : The crate idea is nice but it'd still rather stick to the `std` for the reasons cited above.

I disagree. `fs-err` adds very little overhead yet if something goes wrong, yields a significant improvement in the error message. It _always_ pays off.

>     * **which**  is nice :)
:heavy_check_mark: 

>     * `BuildType::ProfileWithGrcov` and `BuildType::Debug` have been refactored in a way that does not preserve the semantics of the previous code. Now `BuildType::Debug` will compile in `--release` mode which is not correct.

Err, I'll fix that right away.
 
>     * This commit also includes a lot of format changes and other minor changes which I guess might partially come from `cargo fmt` and/or `cargo clippy`. It would be easier to review them in separate and later commits, or better, PRs.

I tried to exclude most of these, but it seems I missed a few.

>     * It seems your PR is based on an obsolete version of `master` because some of the latest changes I made have been deleted by your commit somehow (see [a6cb56d](https://github.com/rust-fuzz/honggfuzz-rs/commit/a6cb56d450751695dd4fe259845800fec24eac94))

Yeah, I think that happend during a rebase.

Going to split this into smaller atomic PRs then.

**Comment by PaulGrandperrin** [comment]
> Mostly went for it since I am in the same situation with docopt, and I like the fact that one writes the help message essentially, the rest is derived. 

I don't get it, why not using `structopt` instead? It is the recommended approach and de-facto standard

> Given today's caching and the time needed to fuzz code vs build time, imho that argument is not really valid for a fuzzing wrapper 

I was thinking about the `cargo build`/`cargo check` time. The vast majority of the time, the devs and the CI will launch these commands without actually starting a fuzzing session. If I am not mistaken, adding dependencies will add to the developer's cycle duration and the CI load. Or it might incentivize them to remove the fuzzing setup code from their check/build path.

> In that case, an explicit encoding with thiserror and error variants might be the better approach. I would rather have it a bit thicker and provide more output as needed.

Indeed but this part of the project is not a library and is basically a small script file with an easy stop-when-there-is-an error approach to error handling. I don't feel it is needed to formalize too much error paths. There is little to gain but code complexity.

> I disagree. fs-err adds very little overhead yet if something goes wrong, yields a significant improvement in the error message. It always pays off.

I don't feel that way. Adding dependencies is always a liability too:
- new versions break stuff
- bugs
- need to periodically check that the project is still maintained
- security issues (intentional or not) and trust are of importance for the kind of people using a fuzzer
- build time

I would love if the `fs-err` devs upstreamed their work to `std`. Moreover, I would already use their crate for projects where difficult-to-debug file errors are a common issue but this is not the case here.
`std` general maintenance quality cannot be understated.

> Going to split this into smaller atomic PRs then.

That would be greatly appreciated, thx :)

**Comment by drahnr** [comment]
> > Mostly went for it since I am in the same situation with docopt, and I like the fact that one writes the help message essentially, the rest is derived.
> 
> I don't get it, why not using `structopt` instead? It is the recommended approach and de-facto standard
> 
> > Given today's caching and the time needed to fuzz code vs build time, imho that argument is not really valid for a fuzzing wrapper
> 
> I was thinking about the `cargo build`/`cargo check` time. The vast majority of the time, the devs and the CI will launch these commands without actually starting a fuzzing session. If I am not mistaken, adding dependencies will add to the developer's cycle duration and the CI load. Or it might incentivize them to remove the fuzzing setup code from their check/build path.
> 
> > In that case, an explicit encoding with thiserror and error variants might be the better approach. I would rather have it a bit thicker and provide more output as needed.
> 
> Indeed but this part of the project is not a library and is basically a small script file with an easy stop-when-there-is-an error approach to error handling. I don't feel it is needed to formalize too much error paths. There is little to gain but code complexity.
> 
> > I disagree. fs-err adds very little overhead yet if something goes wrong, yields a significant improvement in the error message. It always pays off.
> 
> I don't feel that way. Adding dependencies is always a liability too:
> 
>     * new versions break stuff
> 
>     * bugs
> 
>     * need to periodically check that the project is still maintained
> 
>     * security issues (intentional or not) and trust are of importance for the kind of people using a fuzzer
> 
>     * build time
> 
> 
> I would love if the `fs-err` devs upstreamed their work to `std`. Moreover, I would already use their crate for projects where difficult-to-debug file errors are a common issue but this is not the case here.
> `std` general maintenance quality cannot be understated.
> 
> > Going to split this into smaller atomic PRs then.
> 
> That would be greatly appreciated, thx :)

Split it into a bunch of atomic commits, the change of `anyhow` and `docopt` is a bit intertwined to that's one commit right now. Could you note which commits you definitely want, and which ones are a _maybe_ so I don't have to open 7 PRs just to then end up rebasing `n-1` of them :)

**Comment by drahnr** [comment]
I'll replace the `docopt` argparse with `structopt` at some point this week :crossed_fingers:

**Comment by PaulGrandperrin** [comment]
I haven't had the time to look at your other commits yet but I can tell you more about my "philosophy" and plans about the CLI.
I was planning to redesign the CLI interface to make it a little more ergonomic.
Right now the arguments to the wrapper are given on the command line and the arguments to the upstream fuzzer are given through an environment variable. I like that clear separation and I'd like to keep it but I'd like to make it nicer.

My plan was to change from this
```sh
HFUZZ_RUN_ARGS="-v -N 10000000 --run_time 120 --exit_upon_crash" cargo hfuzz run example
```
to this
```sh
cargo hfuzz run example -- -v -N 10000000 --run_time 120 --exit_upon_crash
```
where the delimiter would be `--`.
This is the more standard way that I know for doing that king of things.

**Comment by drahnr** [comment]
> I haven't had the time to look at your other commits yet but I can tell you more about my "philosophy" and plans about the CLI.
> I was planning to redesign the CLI interface to make it a little more ergonomic.
> Right now the arguments to the wrapper are given on the command line and the arguments to the upstream fuzzer are given through an environment variable. I like that clear separation and I'd like to keep it but I'd like to make it nicer.
> 
> My plan was to change from this
> 
> ```shell
> HFUZZ_RUN_ARGS="-v -N 10000000 --run_time 120 --exit_upon_crash" cargo hfuzz run example
> ```

Aware, and this is a rather annoying property of the wrapper right now, since every usage of `honggfuzz` (the lib) requires the same readme repeatedly. So I am all for getting rid of the _requirement_ to pass the options that way and provide an alternative, standard path.

>  This is the more standard way that I know for doing that king of things.

I fully agree. That's what the `docopt` changes also would have impl'd (mostly due to a lack of any different impl).

---

I split this into two PRs, #54  and #53 _without_ docopt since you are already working on the `structopt` impl - I am happy to review that as needed :) or take over if you don't have the time.
The mentioned PRs should go in before the full `structopt` impl or splitting the crate into two.

**Pull request closed without merging**
