### PR TITLE
fix: pass sancov or sancov-module

### PR DESCRIPTION
**Pull request by PsiACE**
Fixes: #61 

The fix for now is to pass `-C passes=sancov-module` to compilers  for which the LLVM version is >= 13.

### CODE REVIEW

**Comment by taiki-e** [comment]
Note that this is currently only needed for the nightly compiler: https://github.com/rust-fuzz/afl.rs/pull/197

**Comment by PsiACE** [comment]
> Note that this is currently only needed for the nightly compiler: [rust-fuzz/afl.rs#197](https://github.com/rust-fuzz/afl.rs/pull/197)

ok, I will change to `version_meta.channel == rustc_version::Channel::Nightly && && version_meta.llvm_version.map_or(true, |v| v.major >= 13)`

**Comment by PsiACE** [comment]
cc @taiki-e , Done!

**Comment by PaulGrandperrin** [comment]
Thanks @taiki-e and @PsiACE for this patch!

And sorry for the looong delay :/

**Pull request merged**
