### PR TITLE
remove linker hack

### PR DESCRIPTION
**Pull request by ordian**
The hack causes troubles for projects utilizing `wasm32-unknown-unknown` targets as rust uses a custom linker [`wasm-lld`](https://github.com/rust-lang/rust/blob/d2b38d6b3c9d1ee52a360c3ce61e54b7aa91d405/src/doc/rustc/src/codegen-options/index.md#linker-flavor) for it.

I don't see any `__sancov_guards` errors when the hack is removed with the recent version of LLVM.

cc https://github.com/rust-lang/rust/issues/53945

### CODE REVIEW

**Comment by ordian** [comment]
I'll close the PR as ubuntu commonly used in CI currently uses an old version of LLVM.

**Comment by PaulGrandperrin** [comment]
Nice! I'll be happy to see this code go :)
I guess the CI is failing because GH Action is still using Ubuntu 18.04 by default, but I tested on my machine which is using 20.04 is it's fine.

**Comment by PaulGrandperrin** [comment]
no, it's fine, I'll force the CI to use Ubuntu 20.04, I think it's reasonable to require a 1year old LTS version of ubuntu

**Comment by ordian** [comment]
I think it has more to do with the llvm version than with Ubuntu's: https://github.com/rust-fuzz/honggfuzz-rs/runs/2096378570#step:1:4.

**Comment by PaulGrandperrin** [comment]
ah yes, they finally changed `ubuntu-latest` to 20.04 so yes it isn't that..
it's working on my 20.04 local machine through.. I'm trying to figure out why

**Comment by PaulGrandperrin** [comment]
I'm back after a little while, but I guess we can now safely remove this hack.
I hope this will solve the issues with wasm! I don't know how to test though..

**Pull request merged**
